# Site settings
title: Wei Zhou Personal Website
description: personal website & portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Hi! I am Wei Zhou,
user_description: Welcome! I am a second year undergrad majoring in Statistics and Computer Science at UChicago. I am currently working on an emotion detection NLP project. For previous projects that I did, please visit my GitHub page.
user_title: Software Developer
email: weiz2623@uchicago.edu
twitter_username:
github_username:  patriciazw2623
gplus_username:

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
